// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2YZyJ2f3mpzu_ZOWUvHbKUyWOf-PKDU',
    appId: '1:214996367965:web:614145e7de5a5728c02bb4',
    messagingSenderId: '214996367965',
    projectId: 'lab17-126e7',
    authDomain: 'lab17-126e7.firebaseapp.com',
    storageBucket: 'lab17-126e7.appspot.com',
    measurementId: 'G-6SWEQ2S359',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0aQziQt1qf-2W3-pdxIJ8BcwP5_Cqrk',
    appId: '1:214996367965:android:21fba519d777fa1dc02bb4',
    messagingSenderId: '214996367965',
    projectId: 'lab17-126e7',
    storageBucket: 'lab17-126e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGsaNe9dY21vf6v4woi6y_3mzkfi49N1o',
    appId: '1:214996367965:ios:57f9d77cc21b1d31c02bb4',
    messagingSenderId: '214996367965',
    projectId: 'lab17-126e7',
    storageBucket: 'lab17-126e7.appspot.com',
    iosBundleId: 'com.example.lab17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGsaNe9dY21vf6v4woi6y_3mzkfi49N1o',
    appId: '1:214996367965:ios:d755394feffd0fbec02bb4',
    messagingSenderId: '214996367965',
    projectId: 'lab17-126e7',
    storageBucket: 'lab17-126e7.appspot.com',
    iosBundleId: 'com.example.lab17.RunnerTests',
  );
}
